# Roxygen renders a method's Arguments section in SIGNATURE order, so a @param
# block that disagrees with the signature still produces correct help. The
# damage is to the source: the next person editing the block sees an argument
# order that contradicts the signature a few lines below, which is how the
# 1.9.0 reorder of MappingsResource$get() came to shift `include_invalid` and
# `vocab_release` out of the positions 1.8.1 had shipped.
#
# For an R6 method, position IS the public contract -- R has no keyword-only
# arguments -- so this guard covers every documented method in the package
# rather than only the ones that have been bitten so far.

#' Extract the R6 generator name a source file defines, or NULL.
generator_name <- function(src) {
  hit <- grep("^[A-Za-z][A-Za-z0-9_.]* <- R6::R6Class\\(", src)
  if (length(hit) != 1) {
    return(NULL)
  }
  sub("^([A-Za-z][A-Za-z0-9_.]*) <- R6::R6Class\\(.*$", "\\1", src[hit])
}

#' @param names, in source order, of the roxygen block directly above `sig`.
documented_params <- function(src, sig) {
  i <- sig - 1
  while (i >= 1 && grepl("^    #'", src[i])) i <- i - 1
  if (i + 1 > sig - 1) {
    return(character(0))
  }
  block <- src[(i + 1):(sig - 1)]
  as.character(
    sub("^    #' @param ([^ ]+).*$", "\\1", grep("^    #' @param ", block, value = TRUE))
  )
}

test_that("every documented R6 method lists @param in signature order", {
  # This reads the package SOURCE, which only exists in a source tree. Under
  # `R CMD check` and `covr` the tests run against an INSTALLED copy, whose R/
  # holds omophub.rdb rather than any .R file -- so the scan would find zero
  # files and, without this skip, fail the check for reasons unrelated to the
  # code. `.github/workflows/R-CMD-check.yaml` runs the guard against the
  # checkout in a separate step so it still gates every PR.
  #
  # One list.files() call feeds both the skip and the scan, so the two cannot
  # drift apart -- e.g. someone widening the pattern in one place only. No
  # dir.exists() guard is needed: list.files() on a missing directory returns
  # character(0) rather than erroring.
  files <- list.files(
    file.path(test_path("..", ".."), "R"),
    pattern = "[.]R$", full.names = TRUE
  )
  skip_if_not(
    length(files) > 0,
    "package source not available (installed-package check)"
  )

  generators_seen <- 0
  for (f in files) {
    src <- readLines(f, warn = FALSE)
    gen_name <- generator_name(src)
    if (is.null(gen_name) || !exists(gen_name)) next
    generator <- get(gen_name)
    generators_seen <- generators_seen + 1

    found <- character(0)
    for (sig in grep("^    [a-zA-Z_.][a-zA-Z0-9_.]* = function\\(", src)) {
      method <- sub("^    ([a-zA-Z_.][a-zA-Z0-9_.]*) = function\\(.*$", "\\1", src[sig])
      fn <- generator$public_methods[[method]]
      if (is.null(fn)) next
      found <- c(found, method)

      # `...` drops out of BOTH sides: documenting it is good practice but
      # optional, and whether a method does is not an ORDER question.
      documented <- setdiff(documented_params(src, sig), "...")
      actual <- setdiff(as.character(names(formals(fn))), "...")

      if (length(documented) == 0L) {
        # Skipping is only legitimate when there is nothing to order. A method
        # that takes arguments and documents none would otherwise slip through
        # this guard silently.
        expect_equal(
          actual, character(0),
          info = sprintf(
            "%s$%s() takes arguments but documents no @param", gen_name, method
          )
        )
        next
      }

      expect_equal(
        documented, actual,
        info = sprintf("%s$%s() in %s", gen_name, method, basename(f))
      )
    }

    # Guard the guard, exactly rather than by a floor: every method the class
    # actually has must have been reached by the scan. An indentation change or
    # a signature the regex cannot see shows up here as a named missing method,
    # and adding or removing a method never needs a hardcoded count updated.
    # `clone` is generated by R6 and has no source block, so it is not expected.
    expect_setequal(found, setdiff(names(generator$public_methods), "clone"))
  }

  # And every R6 class in the package was reached, not just the first. Counted
  # by a deliberately different route than generator_name() uses, so that a bug
  # in its stricter pattern surfaces here instead of quietly shrinking scope.
  classes_in_package <- sum(vapply(
    files,
    function(f) any(grepl("R6::R6Class(", readLines(f, warn = FALSE), fixed = TRUE)),
    logical(1)
  ))
  expect_equal(generators_seen, classes_in_package)
})
